[versions]
fabric-api = "0.145.1+26.1"
fabric-loader = "0.18.6"
fabric-loom = "1.15-SNAPSHOT"
fabric-language-kotlin = "1.13.10+kotlin.2.3.20"
kotlin = "2.3.20"
minecraft = "26.1"
modmenu-badges = "2026.3.1"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu-badges = { module = "maven.modrinth:modmenu-badges-lib", version.ref = "modmenu-badges" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }