[versions]
fabric-api = "0.152.2+26.2"
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
fabric-language-kotlin = "1.13.12+kotlin.2.4.0"
jei = "30.7.0.41"
kotlin = "2.4.0"
minecraft = "26.2"
modmenu-badges = "2026.3.1"

[libraries]
jei-fabric-api = { group = "mezz.jei", name = "jei-26.2-fabric-api", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-26.2-fabric", version.ref = "jei" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu-badges = { module = "maven.modrinth:modmenu-badges-lib", version.ref = "modmenu-badges" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }